# Generated by Django 4.2.20 on 2025-03-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_course_subjects_alter_mark_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.paper'),
        ),
    ]
