# Generated by Django 4.2.20 on 2025-03-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_mark_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='sms.paper'),
        ),
    ]
