# Generated by Django 4.2.20 on 2025-03-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_mark_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.grade'),
        ),
    ]
