# Generated by Django 4.2.21 on 2025-06-04 06:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for identification', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='hero_images')),
                ('caption', models.CharField(blank=True, help_text='Optional caption text', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('button_text', models.CharField(blank=True, default='Get Started', max_length=50)),
                ('button_url', models.CharField(blank=True, default='/services/', max_length=200)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['-display_order'],
            },
        ),
    ]
